# -*- coding: utf-8 -*-
"""0-line

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TcAjpHNYsTgsbr5YN0h77CYJcmsbzMxQ
"""

#!/usr/bin/env python3
"""
Plot y as a line graph:

y should be plotted as a solid red line
The x-axis should range from 0 to 10
"""

import numpy as np
import matplotlib.pyplot as plt

y = np.arange(0, 11) ** 3
# x = np.arange(0, 11)
plt.xlim(0, 10)
plt.plot(x, y, 'r-')  # 'r-' means red solid line

plt.show()