# -*- coding: utf-8 -*-
"""2-change_scale

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eu3Cds870-Kfnr1nH4BcbmhNhXWLl9G3
"""

#!/usr/bin/env python3
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(0, 28651, 5730)
r = np.log(0.5)
t = 5730
y = np.exp((r / t) * x)

# your code here
plt.xlabel("Time (years)")
plt.ylabel("Fraction Remaining")
plt.title("Exponential Decay of C-14")
plt.semilogy(x, y)
plt.xlim(0, 28650)
plt.xticks(np.arange(0, 28651, 5000))
plt.show()