# -*- coding: utf-8 -*-
"""3-two

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xt3rzEtSSazJezpccXlONaVED_wFa99O
"""

#!/usr/bin/env python3
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(0, 21000, 1000)
r = np.log(0.5)
t1 = 5730
t2 = 1600
y1 = np.exp((r / t1) * x)
y2 = np.exp((r / t2) * x)

# your code here
plt.xlabel("Time (years)")
plt.ylabel("Fraction Remaining")
plt.title("Exponential Decay of Radioactive Elements")
plt.xlim(0, 20000)
plt.ylim(0, 1)
plt.plot(x, y1, "--r", x, y2, "-g")
plt.xticks(np.arange(0, 20001, 2500))
plt.yticks(np.arange(0, 1.5, 0.5))
plt.legend(["C-14", "Ra-226"], loc=1)
plt.show()