# -*- coding: utf-8 -*-
"""5-all_in_one

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Dc-9LyCFxjP1ZSCcJnAR2wr4A1po3qt
"""

#!/usr/bin/env python3
import numpy as np
import matplotlib.pyplot as plt


y0 = np.arange(0, 11) ** 3

mean = [69, 0]
cov = [[15, 8], [8, 15]]
np.random.seed(5)
x1, y1 = np.random.multivariate_normal(mean, cov, 2000).T
y1 += 180

x2 = np.arange(0, 28651, 5730)
r2 = np.log(0.5)
t2 = 5730
y2 = np.exp((r2 / t2) * x2)

x3 = np.arange(0, 21000, 1000)
r3 = np.log(0.5)
t31 = 5730
t32 = 1600
y31 = np.exp((r3 / t31) * x3)
y32 = np.exp((r3 / t32) * x3)

np.random.seed(5)
student_grades = np.random.normal(68, 15, 50)
max_max = int(np.ceil(student_grades.max() / 10) * 10)


fig = plt.figure(figsize=(8, 8))
fig.suptitle('All in One', fontsize='medium')

# plot 0
ax = plt.subplot2grid((3, 2), (0, 0), rowspan=1, colspan=1)
ax.plot(y0, color='red')
ax.set_xlim(0, 10)
ax.set_xticks(np.arange(0, 11, 2))
ax.set_ylim(-50, 1100)
ax.set_yticks(np.arange(0, 1020, 500))


# plot 1
ax = plt.subplot2grid((3, 2), (0, 1), rowspan=1, colspan=1)
ax.scatter(x1, y1, c='magenta', s=6)
ax.set_xlim(55, 85)
ax.set_xticks(np.arange(60, 90, 10))
ax.set_ylim(160, 195)
ax.set_yticks(np.arange(170, 191, 10))
ax.set_title("Men's Height vs Weight", fontsize='x-small')
ax.set_xlabel('Height (in)', fontsize='x-small')
ax.set_ylabel('Weight (lbs)', fontsize='x-small')

# plot 2
ax = plt.subplot2grid((3, 2), (1, 0), rowspan=1, colspan=1)
ax.semilogy(x2, y2)
ax.set_xlim(0, 28650)
ax.set_xticks(np.arange(0, 28651, 10000))
ax.set_title('Exponential Decay of C-14', fontsize='x-small')
ax.set_xlabel('Time (years)', fontsize='x-small')
ax.set_ylabel('Fraction Remaining', fontsize='x-small')

# plot 3
ax = plt.subplot2grid((3, 2), (1, 1), rowspan=1, colspan=1)
ax.plot(x3, y31, '--r', label='C-14')
ax.plot(x3, y32, '-g', label='Ra-226')
ax.set_xlim(0, 20000)
ax.set_xticks(np.arange(0, 20001, 5000))
ax.set_ylim(0, 1)
ax.set_yticks(np.arange(0, 1.5, 0.5))
ax.set_title('Exponential Decay of Radioactive Elements', fontsize='x-small')
ax.set_xlabel('Time (years)', fontsize='x-small')
ax.set_ylabel('Fraction Remaining', fontsize='x-small')
ax.legend(fontsize='x-small', loc='upper right')

# plot 4
ax = plt.subplot2grid((3, 2), (2, 0), rowspan=1, colspan=2)
ax.hist(student_grades, bins=np.arange(0, max_max + 1, 10), edgecolor='black')
ax.set_xlim(0, 100)
ax.set_xticks(np.arange(0, 101, 10))
ax.set_ylim(0, 30)
ax.set_yticks(np.arange(0, 31, 10))
ax.set_title('Project A', fontsize='x-small')
ax.set_xlabel('Grades', fontsize='x-small')
ax.set_ylabel('Number of Students', fontsize='x-small')

# Adjust layout
fig.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()